services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: codebase-explorer-backend:latest
    container_name: backend
    volumes:
      - .:/app:cached
      - ./storage:/app/storage
      - ./models:/app/models:cached
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-exclude node_modules
      --reload-exclude dist
      --reload-exclude .git
      --reload-exclude storage
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: codebase-explorer-frontend:latest
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: unless-stopped