version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: codebase-explorer-backend:latest
    volumes:
      - .:/app:cached
      - ./storage:/app/storage
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-exclude node_modules
      --reload-exclude dist
      --reload-exclude .git
      --reload-exclude frontend
      --reload-exclude storage

  frontend:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend